ALSA lib pcm_dsnoop.c:601:(snd_pcm_dsnoop_open) unable to open slave
ALSA lib pcm_dmix.c:1032:(snd_pcm_dmix_open) unable to open slave
ALSA lib pcm.c:2664:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.rear
ALSA lib pcm.c:2664:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.center_lfe
ALSA lib pcm.c:2664:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.side
ALSA lib pcm_oss.c:397:(_snd_pcm_oss_open) Cannot open device /dev/dsp
ALSA lib pcm_oss.c:397:(_snd_pcm_oss_open) Cannot open device /dev/dsp
ALSA lib confmisc.c:160:(snd_config_get_card) Invalid field card
ALSA lib pcm_usb_stream.c:482:(_snd_pcm_usb_stream_open) Invalid card 'card'
ALSA lib confmisc.c:160:(snd_config_get_card) Invalid field card
ALSA lib pcm_usb_stream.c:482:(_snd_pcm_usb_stream_open) Invalid card 'card'
ALSA lib pcm_dmix.c:1032:(snd_pcm_dmix_open) unable to open slave
ALSA lib pcm.c:8568:(snd_pcm_recover) underrun occurred
Traceback (most recent call last):
  File "/home/sreyas/Documents/computer_networks/Networks-Lab2/reciver.py", line 424, in <module>
    dll_layer.recieve()
  File "/home/sreyas/Documents/computer_networks/Networks-Lab2/reciver.py", line 353, in recieve
    sender=self.rec_rts()
  File "/home/sreyas/Documents/computer_networks/Networks-Lab2/reciver.py", line 301, in rec_rts
    bit =   self.read_signal()
  File "/home/sreyas/Documents/computer_networks/Networks-Lab2/reciver.py", line 127, in read_signal
    rawData = self.stream.read(numSamples)
  File "/home/sreyas/.local/lib/python3.10/site-packages/pyaudio/__init__.py", line 570, in read
    return pa.read_stream(self._stream, num_frames,
KeyboardInterrupt
